-- Tesouraria Martinho Lutero - V19
-- 13º de ofertas + módulo PDV com permissões independentes

ALTER TABLE public.ofertas
  ADD COLUMN IF NOT EXISTS decimo_terceiro boolean NOT NULL DEFAULT false;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS acesso_ofertas boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS acesso_pdv boolean NOT NULL DEFAULT false;

UPDATE public.profiles SET acesso_ofertas = true WHERE acesso_ofertas IS NULL;
UPDATE public.profiles SET acesso_pdv = false WHERE acesso_pdv IS NULL;

CREATE OR REPLACE FUNCTION public.can_access_offers()
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path=public STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.ativo = true
      AND (p.role = 'admin' OR p.acesso_ofertas = true)
  );
$$;

CREATE OR REPLACE FUNCTION public.can_access_pdv()
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path=public STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.ativo = true
      AND (p.role = 'admin' OR p.acesso_pdv = true)
  );
$$;

-- PDV
CREATE TABLE IF NOT EXISTS public.pdv_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  data_evento date NOT NULL DEFAULT CURRENT_DATE,
  ativo boolean NOT NULL DEFAULT true,
  criado_por uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pdv_produtos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  preco numeric(12,2) NOT NULL DEFAULT 0 CHECK (preco >= 0),
  estoque integer NOT NULL DEFAULT 0 CHECK (estoque >= 0),
  ativo boolean NOT NULL DEFAULT true,
  criado_por uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pdv_vendas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id bigint NOT NULL REFERENCES public.pdv_eventos(id) ON DELETE RESTRICT,
  numero text,
  forma_pagamento text NOT NULL DEFAULT 'dinheiro' CHECK (forma_pagamento IN ('dinheiro','pix','cartao','outro')),
  total numeric(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  status text NOT NULL DEFAULT 'finalizada' CHECK (status IN ('finalizada','cancelada')),
  criado_por uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pdv_itens_venda (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id bigint NOT NULL REFERENCES public.pdv_vendas(id) ON DELETE CASCADE,
  produto_id bigint NOT NULL REFERENCES public.pdv_produtos(id) ON DELETE RESTRICT,
  quantidade integer NOT NULL CHECK (quantidade > 0),
  preco_unitario numeric(12,2) NOT NULL CHECK (preco_unitario >= 0),
  subtotal numeric(12,2) NOT NULL CHECK (subtotal >= 0)
);

CREATE INDEX IF NOT EXISTS idx_pdv_vendas_evento ON public.pdv_vendas(evento_id);
CREATE INDEX IF NOT EXISTS idx_pdv_itens_venda ON public.pdv_itens_venda(venda_id);

ALTER TABLE public.pdv_eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdv_produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdv_vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdv_itens_venda ENABLE ROW LEVEL SECURITY;

-- Recria as políticas do módulo PDV de forma explícita.
DROP POLICY IF EXISTS pdv_eventos_select ON public.pdv_eventos;
DROP POLICY IF EXISTS pdv_eventos_insert ON public.pdv_eventos;
DROP POLICY IF EXISTS pdv_eventos_update ON public.pdv_eventos;
DROP POLICY IF EXISTS pdv_eventos_delete ON public.pdv_eventos;
DROP POLICY IF EXISTS pdv_produtos_select ON public.pdv_produtos;
DROP POLICY IF EXISTS pdv_produtos_insert ON public.pdv_produtos;
DROP POLICY IF EXISTS pdv_produtos_update ON public.pdv_produtos;
DROP POLICY IF EXISTS pdv_produtos_delete ON public.pdv_produtos;
DROP POLICY IF EXISTS pdv_vendas_select ON public.pdv_vendas;
DROP POLICY IF EXISTS pdv_vendas_insert ON public.pdv_vendas;
DROP POLICY IF EXISTS pdv_itens_select ON public.pdv_itens_venda;

CREATE POLICY pdv_eventos_select ON public.pdv_eventos FOR SELECT USING (public.can_access_pdv());
CREATE POLICY pdv_eventos_insert ON public.pdv_eventos FOR INSERT WITH CHECK (public.can_access_pdv());
CREATE POLICY pdv_eventos_update ON public.pdv_eventos FOR UPDATE USING (public.can_access_pdv()) WITH CHECK (public.can_access_pdv());
CREATE POLICY pdv_eventos_delete ON public.pdv_eventos FOR DELETE USING (public.is_admin());

CREATE POLICY pdv_produtos_select ON public.pdv_produtos FOR SELECT USING (public.can_access_pdv());
CREATE POLICY pdv_produtos_insert ON public.pdv_produtos FOR INSERT WITH CHECK (public.can_access_pdv());
CREATE POLICY pdv_produtos_update ON public.pdv_produtos FOR UPDATE USING (public.can_access_pdv()) WITH CHECK (public.can_access_pdv());
CREATE POLICY pdv_produtos_delete ON public.pdv_produtos FOR DELETE USING (public.is_admin());

CREATE POLICY pdv_vendas_select ON public.pdv_vendas FOR SELECT USING (public.can_access_pdv());
CREATE POLICY pdv_vendas_insert ON public.pdv_vendas FOR INSERT WITH CHECK (public.can_access_pdv());
CREATE POLICY pdv_itens_select ON public.pdv_itens_venda FOR SELECT USING (public.can_access_pdv());

-- Venda atômica: confere estoque, cria venda, cria itens e baixa estoque na mesma transação.
CREATE OR REPLACE FUNCTION public.registrar_venda_pdv(
  p_evento_id bigint,
  p_forma_pagamento text,
  p_itens jsonb
) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_venda_id bigint;
  v_total numeric(12,2) := 0;
  item jsonb;
  v_produto public.pdv_produtos%ROWTYPE;
  v_qtd integer;
  v_preco numeric(12,2);
BEGIN
  IF NOT public.can_access_pdv() THEN RAISE EXCEPTION 'Acesso ao PDV não autorizado'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.pdv_eventos WHERE id=p_evento_id AND ativo=true) THEN RAISE EXCEPTION 'Evento inválido ou inativo'; END IF;
  IF p_forma_pagamento NOT IN ('dinheiro','pix','cartao','outro') THEN RAISE EXCEPTION 'Forma de pagamento inválida'; END IF;
  IF jsonb_typeof(p_itens) <> 'array' OR jsonb_array_length(p_itens)=0 THEN RAISE EXCEPTION 'Venda sem itens'; END IF;

  FOR item IN SELECT * FROM jsonb_array_elements(p_itens) LOOP
    SELECT * INTO v_produto FROM public.pdv_produtos WHERE id=(item->>'produto_id')::bigint AND ativo=true FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Produto não encontrado'; END IF;
    v_qtd := (item->>'quantidade')::integer;
    IF v_qtd IS NULL OR v_qtd <= 0 THEN RAISE EXCEPTION 'Quantidade inválida'; END IF;
    IF v_produto.estoque < v_qtd THEN RAISE EXCEPTION 'Estoque insuficiente para: %', v_produto.nome; END IF;
    v_preco := v_produto.preco;
    v_total := v_total + (v_preco * v_qtd);
  END LOOP;

  INSERT INTO public.pdv_vendas(evento_id, numero, forma_pagamento, total, criado_por)
  VALUES(p_evento_id, NULL, p_forma_pagamento, v_total, auth.uid())
  RETURNING id INTO v_venda_id;
  UPDATE public.pdv_vendas SET numero = 'PDV-' || v_venda_id WHERE id=v_venda_id;

  FOR item IN SELECT * FROM jsonb_array_elements(p_itens) LOOP
    SELECT * INTO v_produto FROM public.pdv_produtos WHERE id=(item->>'produto_id')::bigint FOR UPDATE;
    v_qtd := (item->>'quantidade')::integer;
    INSERT INTO public.pdv_itens_venda(venda_id,produto_id,quantidade,preco_unitario,subtotal)
    VALUES(v_venda_id,v_produto.id,v_qtd,v_produto.preco,v_produto.preco*v_qtd);
    UPDATE public.pdv_produtos SET estoque=estoque-v_qtd, atualizado_em=now() WHERE id=v_produto.id;
  END LOOP;
  RETURN v_venda_id;
END; $$;

REVOKE ALL ON FUNCTION public.registrar_venda_pdv(bigint,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_venda_pdv(bigint,text,jsonb) TO authenticated;

-- IMPORTANTE: depois de executar esta migração, substitua as políticas atuais de ofertas
-- para exigir can_access_offers(), caso elas ainda estejam abertas para qualquer autenticado.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='ofertas' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.ofertas', r.policyname);
  END LOOP;
END $$;
CREATE POLICY ofertas_select_access ON public.ofertas FOR SELECT USING (public.can_access_offers());
CREATE POLICY ofertas_insert_access ON public.ofertas FOR INSERT WITH CHECK (public.can_access_offers());
CREATE POLICY ofertas_update_access ON public.ofertas FOR UPDATE USING (public.can_access_offers()) WITH CHECK (public.can_access_offers());
CREATE POLICY ofertas_delete_access ON public.ofertas FOR DELETE USING (public.can_access_offers());


-- Bloqueia também os dados auxiliares da tesouraria para perfis PDV-only.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT policyname, tablename FROM pg_policies
    WHERE schemaname='public' AND tablename IN ('cultos','ofertantes','configuracoes') LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END $$;
CREATE POLICY cultos_select_offers ON public.cultos FOR SELECT USING (public.can_access_offers());
CREATE POLICY cultos_insert_offers ON public.cultos FOR INSERT WITH CHECK (public.can_access_offers());
CREATE POLICY cultos_update_offers ON public.cultos FOR UPDATE USING (public.can_access_offers()) WITH CHECK (public.can_access_offers());
CREATE POLICY cultos_delete_offers ON public.cultos FOR DELETE USING (public.can_access_offers());
CREATE POLICY ofertantes_select_offers ON public.ofertantes FOR SELECT USING (public.can_access_offers());
CREATE POLICY ofertantes_insert_offers ON public.ofertantes FOR INSERT WITH CHECK (public.can_access_offers());
CREATE POLICY ofertantes_update_offers ON public.ofertantes FOR UPDATE USING (public.can_access_offers()) WITH CHECK (public.can_access_offers());
CREATE POLICY ofertantes_delete_offers ON public.ofertantes FOR DELETE USING (public.can_access_offers());
CREATE POLICY configuracoes_select_offers ON public.configuracoes FOR SELECT USING (public.can_access_offers());
CREATE POLICY configuracoes_insert_admin ON public.configuracoes FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY configuracoes_update_admin ON public.configuracoes FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY configuracoes_delete_admin ON public.configuracoes FOR DELETE USING (public.is_admin());
